using System;

namespace JewishCalendarUWP.Parsha
{
    public class Enum
    {
        public enum TorahPortion
        {
            Bereshit = 1,
            Noach,
            Lech_Lecha,
            Vayera,
            Chayei_Sara,
            Toldot,
            Vayetzei,
            Vayishlach,
            Vayeshev,
            Miketz,
            Vayigash,
            Vayechi,
            Shemot,
            Vaera,
            Bo,
            Beshalach,
            Yitro,
            Mishpatim,
            Terumah,
            Tetzaveh,
            Ki_Tisa,
            Vayakhel,
            Pekudei,
            Vayikra,
            Tzav,
            Shmini,
            Tazria,
            Metzora,
            Achrei_Mot,
            Kedoshim,
            Emor,
            Behar,
            Bechukotai,
            Bamidbar,
            Nasso,
            Behaalotcha,
            Shlach,
            Korach,
            Chukat,
            Balak,
            Pinchas,
            Matot,
            Masei,
            Devarim,
            Vaetchanan,
            Eikev,
            ReEh,
            Shoftim,
            Ki_Teitzei,
            Ki_Tavo,
            Nitzavim,
            Vayeilech,
            HaAzinu,
            Vezot_Haberakhah,
            Vayakhel_Pekudei,
            Tazria_Metzora,
            Achrei_Mot_Kedoshim,
            Behar_Bechukotai,
            Chukat_Balak,
            Matot_Masei,
            Nitzavim_Vayeilech,

        }
    }
}
